version: '3.9'

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: chiliconcarne101usr
      POSTGRES_PASSWORD: chiliconcarne101pwd
      POSTGRES_DB: gwas2eqtl
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - vol_data_postgres:/var/lib/postgresql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "dbvarnoncod", "-d", "dbvarnoncod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    depends_on:
      - postgres

volumes:
  vol_data_postgres:
